# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"6\n\x07\x43hannel\x12\x12\n\nchanelName\x18\x01 \x01(\t\x12\x17\n\x06\x63lient\x18\x02 \x01(\x0b\x32\x07.Client\"\x16\n\x06\x43lient\x12\x0c\n\x04name\x18\x01 \x01(\t\"I\n\x07Message\x12\x15\n\x04\x66rom\x18\x01 \x01(\x0b\x32\x07.Client\x12\x19\n\x07\x63hannel\x18\x02 \x01(\x0b\x32\x08.Channel\x12\x0c\n\x04text\x18\x03 \x01(\t\"g\n\x08Response\x12\x1b\n\x04type\x18\x01 \x01(\x0e\x32\r.ResponseType\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07message\x18\x03 \x01(\t*~\n\x0cResponseType\x12\x08\n\x04SENT\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x12\x0f\n\x0bISCONNECTED\x10\x02\x12\n\n\x06JOINED\x10\x03\x12\x08\n\x04LEFT\x10\x04\x12\x10\n\x0c\x44ISCONNECTED\x10\x05\x12\x0c\n\x08RECIEVED\x10\x06\x12\x11\n\rALREADY_EXIST\x10\x07\x32\xeb\x01\n\x0c\x43hatServices\x12#\n\tconnexion\x12\x07.Client\x1a\t.Response(\x01\x30\x01\x12$\n\ndisconnect\x12\x07.Client\x1a\t.Response(\x01\x30\x01\x12\x1f\n\x04join\x12\x08.Channel\x1a\t.Response(\x01\x30\x01\x12%\n\nlistClient\x12\x08.Channel\x1a\t.Response(\x01\x30\x01\x12 \n\x05leave\x12\x08.Channel\x1a\t.Response(\x01\x30\x01\x12&\n\x0bsendMessage\x12\x08.Message\x1a\t.Response(\x01\x30\x01\x42\x10\n\x0ema.enset.stubsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\016ma.enset.stubs'
  _RESPONSETYPE._serialized_start=307
  _RESPONSETYPE._serialized_end=433
  _CHANNEL._serialized_start=47
  _CHANNEL._serialized_end=101
  _CLIENT._serialized_start=103
  _CLIENT._serialized_end=125
  _MESSAGE._serialized_start=127
  _MESSAGE._serialized_end=200
  _RESPONSE._serialized_start=202
  _RESPONSE._serialized_end=305
  _CHATSERVICES._serialized_start=436
  _CHATSERVICES._serialized_end=671
# @@protoc_insertion_point(module_scope)
